# Site settings
title: Kristoffer Hedstrom | k-create
email: kris@k-create.com
description: "Kristoffer Hedstrom is a Swedish interactive designer and developer living in Brooklyn, NY."
baseurl: ""
asseturl: "http://localhost:8080"
url: "http://k-create.com"
name: Kristoffer Hedstrom
ogimage: ""
fbadmin: ""
datasource: "./data"

# Build settings
production: false
markdown: kramdown
permalink: /:year/:month/:day/:title/
sass:
    style: :compressed
exclude:
    - node_modules
    - tasks
include: ["data"]
