# Site settings
title: K-Create | Kristoffer Hedstrom
email: kris@k-create.com
description: "Kristoffer Hedstrom is a Swedish interactive designer and developer living in Brooklyn, NY."
baseurl: ""
asseturl: ""
url: "http://k-create.com"

# Build settings
production: true
markdown: kramdown
permalink: /:year/:month/:day/:title/
sass:
    style: :compressed
exclude:
    - node_modules
    - tasks
